name: preprocess_raw_viability
description: Module to make the raw viability data fitting for CurveCurator.
keywords:
  - curve curator
  - viability data
  - refitting
  - preprocessing
tools:
  - drevalpy:
      description: |
        drevalpy is the package underlying nf-core/drugresponseeval. It provides a framework for fair and
        coherent training and evaluation of monotherapy drug response prediction models.
      homepage: https://github.com/daisybio/drevalpy/
      documentation: https://drevalpy.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/daisybio/drevalpy/
      doi: "10.1101/2025.05.26.655288"
      licence: ["MIT"]
      identifier: ""

input:
  - dataset_name:
      type: string
      description: Name of the dataset that will be reprocessed by CurveCurator.
  - work_path:
      type: file
      description: The raw file is expected at
        {work_path}/{dataset_name}/{dataset_name}_raw.csv

output:
  path_to_toml:
    - "${dataset_name}/*/config.toml":
        type: file
        description: Configuration file for CurveCurator.
        pattern: "*.toml"
  curvecurator_input:
    - "${dataset_name}/*/curvecurator_input.tsv":
        type: file
        description: Input file for CurveCurator with samples, drugs, doses, and
          replicates.
        pattern: "*.tsv"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/python_pip_drevalpy:07cdd5a85ef96789
      buildId: bd-07cdd5a85ef96789_1
      scanId: sc-973f6f00d423213e_1
    linux/arm64:
      name: community.wave.seqera.io/library/python_pip_drevalpy:73a364e6a61f3951
      buildId: bd-73a364e6a61f3951_1
      scanId: sc-ae9f02412bc90df3_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/python_pip_drevalpy:1069f505cb1315b2
      buildId: bd-1069f505cb1315b2_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/3f/3f8fdc4bf25d3160c2b44a1c628d34bcc01c292c51b3e8f6232c927eb985109b/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/python_pip_drevalpy:9257eb86bb296106
      buildId: bd-9257eb86bb296106_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/f8/f86188574968e43df4813ad20d8d083761a124930c6335a6bb4cca0553e31680/data
  conda:
    linux/amd64:
      lock_file: modules/local/preprocess_raw_viability/.conda-lock/linux-amd64-bd-07cdd5a85ef96789_1.txt
    linux/arm64:
      lock_file: modules/local/preprocess_raw_viability/.conda-lock/linux-arm64-bd-73a364e6a61f3951_1.txt
