---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: final_split
description: Make splits to train a final model on the full dataset for future predictions.
keywords:
  - final model
  - training validation split
  - model training
tools:
  - drevalpy:
      description: |
        drevalpy is the package underlying nf-core/drugresponseeval. It provides a framework for fair and
        coherent training and evaluation of monotherapy drug response prediction models.
      homepage: https://github.com/daisybio/drevalpy/
      documentation: https://drevalpy.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/daisybio/drevalpy/
      doi: "10.1101/2025.05.26.655288"
      licence: ["MIT"]
      identifier: ""

input:
  - - model_name:
        type: string
        description: Name of the model. Used to find out whether the model is a single-drug model.
    - response:
        type: file
        description: |
          Pickled, complete DrugResponseDataset that will be split into a final
          training and validation dataset.
    - test_mode:
        type: string
        description: Specifies the test mode. One of LPO, LCO, LTO, LDO.
    - path_data:
        type: file
        description: |
          Path to the (downloaded/custom) input data directory. Used to load the cell line and drug features of the
          specified model to reduce the response dataset to the rows for which the model can generate features.

output:
  final_datasets:
    - - model_name:
          type: string
          description: See input.
      - "training_dataset.pkl":
          type: file
          description: Pickled training dataset.
          pattern: "training_dataset.pkl"
      - "validation_dataset.pkl":
          type: file
          description: Pickled validation dataset.
          pattern: "validation_dataset.pkl"
      - "early_stopping_dataset.pkl":
          type: file
          description: Pickled early stopping dataset, if the model requires one.
          pattern: "early_stopping_dataset.pkl"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
containers:
  conda:
    linux/amd64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-a7cebe5b9fa462ea_1/condalock
    linux/arm64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-efdcf01a3b56c2ab_2/condalock
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:e3225eb976969752
      build_id: bd-e3225eb976969752_3
    linux/arm64:
      name: community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:efdcf01a3b56c2ab
      build_id: bd-efdcf01a3b56c2ab_2
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:a7cebe5b9fa462ea
      build_id: bd-a7cebe5b9fa462ea_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/b3/b3c7537ef89d5160d212fea27f38dbe8e7846dda288bc451d9612ea88dd2a715/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:e1fbe7eefaa8d0b7
      build_id: bd-e1fbe7eefaa8d0b7_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/70/70b4089063c4861beb0a9e697415b5a6a891f8c3cac468efb04610fa023aef16/data
