---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: visualize_results
description: Makes the interactive HTML results plots and files.
keywords:
  - visualization
  - interactive
  - html
  - results
  - exploration
tools:
  - drevalpy:
      description: |
        drevalpy is the package underlying nf-core/drugresponseeval. It provides a framework for fair and
        coherent training and evaluation of monotherapy drug response prediction models.
      homepage: https://github.com/daisybio/drevalpy/
      documentation: https://drevalpy.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/daisybio/drevalpy/
      doi: "10.1101/2025.05.26.655288"
      licence: ["MIT"]
      identifier: ""

input:
  - - eval_results:
        type: file
        description: Global evaluation results.
        pattern: "*csv"
    - eval_results_per_drug:
        type: file
        description: Evaluation results per drug.
        pattern: "*csv"
    - eval_results_per_cl:
        type: file
        description: Evaluation results per cell line.
        pattern: "*csv"
    - true_vs_predicted:
        type: file
        description: True vs. predicted values.
        pattern: "*csv"
  - path_data:
      type: string
      description: Path to the data.

output:
  html_out:
    - "report/*":
        type: file
        description: Folder containing all report-related files.
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
containers:
  conda:
    linux/amd64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-15b789664f3bd82d_1/condalock
    linux/arm64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-3e0785b5b12ace5a_1/condalock
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:15b789664f3bd82d
      build_id: bd-e3225eb976969752_3
    linux/arm64:
      name: community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:3e0785b5b12ace5a
      build_id: bd-3e0785b5b12ace5a_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:3a2daab6f1669afe
      build_id: bd-15b789664f3bd82d_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/6d/6dd942756556d881b3522aef53f63d24a977606d6dc629d23228f462c76a0dc6/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:de41fc123c6283bd
      build_id: bd-e1fbe7eefaa8d0b7_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/e4/e44bca044cacb8ef8eec56fc6414832e3c6f4c65e98546ceb827c7ac9d5392a5/data
