---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: collect_results
description: Collects results
keywords:
  - collection
  - results
  - summary
tools:
  - drevalpy:
      description: |
        drevalpy is the package underlying nf-core/drugresponseeval. It provides a framework for fair and
        coherent training and evaluation of monotherapy drug response prediction models.
      homepage: https://github.com/daisybio/drevalpy/
      documentation: https://drevalpy.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/daisybio/drevalpy/
      doi: "10.1101/2025.05.26.655288"
      licence: ["MIT"]
      identifier: ""

input:
  - outfiles:
      type: file
      description: |
        List of individual evaluation files, following the pattern '{model_name}_evaluation_results.csv',
        '{model_name}_evaluation_results_per_drug.csv', '{model_name}_evaluation_results_per_cl.csv',
        and '{model_name}_true_vs_pred.csv'. Will be collected to form 4 combined result files.
  - path_data:
      type: file
      description: |
        Path to the (downloaded or custom) input data. Used to look for drug_names.csv and
        cell_line_names.csv to add the metadata to the result files.

output:
  evaluation_results:
    - "evaluation_results.csv":
        type: file
        description: combined results from all '{model_name}_evaluation_results.csv'
        pattern: "evaluation_results.csv"
  evaluation_results_per_drug:
    - "evaluation_results_per_drug.csv":
        type: file
        description: combined results from all '{model_name}_evaluation_results_per_drug.csv'
        pattern: "evaluation_results_per_drug.csv"
  evaluation_results_per_cl:
    - "evaluation_results_per_cl.csv":
        type: file
        description: combined results from all '{model_name}_evaluation_results_per_cl.csv'
        pattern: "evaluation_results_per_cl.csv"
  true_vs_pred:
    - "true_vs_pred.csv":
        type: file
        description: combined results from all '{model_name}_true_vs_pred.csv'
        pattern: "true_vs_pred.csv"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
