name: evaluate_find_max
description: |
  Evaluates the results of all cross-validation splits to find
  the best-performing hyperparameter combination.
keywords:
  - collection
  - results
  - single-drug
tools:
  - drevalpy:
      description: |
        drevalpy is the package underlying nf-core/drugresponseeval. It provides a framework for fair and
        coherent training and evaluation of monotherapy drug response prediction models.
      homepage: https://github.com/daisybio/drevalpy/
      documentation: https://drevalpy.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/daisybio/drevalpy/
      doi: "10.1101/2025.05.26.655288"
      licence: ["MIT"]
      identifier: ""

input:
  - - model_name:
        type: string
        description: Name of the model. Used to find out whether the model is a
          single-drug model.
    - test_mode:
        type: string
        description: Specifies the test mode. One of LPO, LCO, LTO, LDO.
    - split_id:
        type: string
        description: Cross-validation split being evaluated, e.g., "split_0".
    - hpam_yamls:
        type: file
        description: Contain the individual hyperparameter configurations.
        pattern: "*.yaml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
    - pred_datas:
        type: file
        description: |
          Pickled DrugResponseDataset containing the true and predicted drug responses for the models in their
          hyperparameter configurations. Used to evaluate the performance of each hyperparameter configuration
          to identify the best one.
  - metric:
      type: string
      description: |
        Hyperparameter optimization metric used to evaluate the performance
        (e.g., MSE, RMSE, MAE, R^2, Pearson).

output:
  best_combis:
    - - model_name:
          type: string
          description: See input.
      - split_id:
          type: string
          description: See input.
      - test_mode:
          type: string
          description: See input.
      - "best_hpam_combi_*.yaml":
          type: file
          description: |
            Yaml containing the best hyperparameter combination. Structure:
            "{model_name}_{split_id}": {"best_hpam_combi": best_hpam_combi, "best_result": best_result}
          pattern: "best_hpam_combi_*.yaml"
          ontologies:
            - edam: http://edamontology.org/format_3750 # YAML
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/python_pip_drevalpy:af9bf54ab78b9680
      buildId: bd-af9bf54ab78b9680_2
      scanId: sc-b6d2bf0ab809292d_1
    linux/arm64:
      name: community.wave.seqera.io/library/python_pip_drevalpy:c833eff049957dc2
      buildId: bd-c833eff049957dc2_1
      scanId: sc-4f679c779337d3be_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/python_pip_drevalpy:14f6aa7ce515f298
      buildId: bd-14f6aa7ce515f298_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/c3/c38ed8e928ffd441f865d16ada04b42aebbeaafb7b630e6b89f19593ebd92537/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/python_pip_drevalpy:71ba1f0f872b5905
      buildId: bd-71ba1f0f872b5905_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/d3/d34593b3682b661bcdb45c4d7387af50d99766b643c5ea5a792b38ef41379f6b/data
  conda:
    linux/amd64:
      lock_file: modules/local/evaluate_find_max/.conda-lock/linux-amd64-bd-af9bf54ab78b9680_2.txt
    linux/arm64:
      lock_file: modules/local/evaluate_find_max/.conda-lock/linux-arm64-bd-c833eff049957dc2_1.txt
