---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: load_response
description: Loads a drug response dataset from {path_data}/{dataset_name.csv} and pickles it.
keywords:
  - drug response dataset
  - data loader
  - pickle
tools:
  - drevalpy:
      description: |
        drevalpy is the package underlying nf-core/drugresponseeval. It provides a framework for fair and
        coherent training and evaluation of monotherapy drug response prediction models.
      homepage: https://github.com/daisybio/drevalpy/
      documentation: https://drevalpy.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/daisybio/drevalpy/
      doi: "10.1101/2025.05.26.655288"
      licence: ["MIT"]
      identifier: ""

input:
  - - measure:
        type: string
        description: Which column of the response dataset should be loaded, e.g., LN_IC50, pEC50, AUC.
    - response:
        type: file
        description: Path to the response dataset, i.e.,{path_data}/{dataset_name.csv}.
        pattern: "*.csv"
  - cross_study_dataset:
      type: boolean
      description: Whether the loaded dataset will be used for cross-study prediction.

output:
  response_dataset:
    - "response_dataset.pkl":
        type: file
        description: |
          Pickled DrugResponseDataset, contains the data that will be used for training, validation, testing.
        pattern: "response_dataset.pkl"
  cross_study_datasets:
    - "cross_study_*.pkl":
        type: file
        description: |
          Pickled DrugResponseDataset, contains the data for cross-study generalization if cross_study_dataset was true.
        pattern: "cross_study_*.pkl"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
