channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::matplotlib=3.11.2
  - conda-forge::numpy=2.5.3
  - conda-forge::pandas=2.3.3
  - conda-forge::python=3.13.13
  - conda-forge::scikit-learn=1.9.1
  - conda-forge::scipy=1.18.1
  - pip
  - pip:
      - drevalpy==1.6.0
      - pytorch-lightning==2.6.6
      - torch==2.14.0
      - scikit-posthocs==0.17.0
