---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: randomization_split
description: Creates yaml configuration files to spawn one process per randomization experiment.
keywords:
  - randomization
  - preprocessing
  - setup
tools:
  - drevalpy:
      description: |
        drevalpy is the package underlying nf-core/drugresponseeval. It provides a framework for fair and
        coherent training and evaluation of monotherapy drug response prediction models.
      homepage: https://github.com/daisybio/drevalpy/
      documentation: https://drevalpy.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/daisybio/drevalpy/
      doi: "10.1101/2025.05.26.655288"
      licence: ["MIT"]
      identifier: ""

input:
  - - model_name:
        type: string
        description: Name of the model for which the randomization experiments will be made.
    - randomization_mode:
        type: string
        description: Could be SVRC, SVRD, SVCC, SVCD.

output:
  randomization_test_views:
    - - model_name:
          type: string
          description: See input.
      - "randomization_test_view*.yaml":
          type: file
          description: |
            YAML files containing the different randomization experiments.
          pattern: "randomization_test_view*.yaml"
          ontologies:
            - edam: http://edamontology.org/format_3750 # YAML
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
containers:
  conda:
    linux/amd64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-0868f8788117e11b_1/condalock
    linux/arm64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-b9be8869b9baf043_1/condalock
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:0868f8788117e11b
      build_id: bd-0868f8788117e11b_1
    linux/arm64:
      name: community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:b9be8869b9baf043
      build_id: bd-b9be8869b9baf043_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:4b5a559039349628
      build_id: bd-4b5a559039349628_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/90/908156ca5b3770a1797cd6f564cea34935ab7b09b39643436494f3bdf6331266/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:5ece055ed10da168
      build_id: bd-5ece055ed10da168_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/58/58bcddaaf126fea865e5b9d7e0cb61bbb4fc162127120fb53b1ed3921c9e9b15/data
