---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: make_model_channel
description: |
  Takes the model names and emits a txt, either one with a list of all models,
  or one with a list of all baselines.
keywords:
  - model names
  - helper function
  - baselines
tools:
  - drevalpy:
      description: |
        drevalpy is the package underlying nf-core/drugresponseeval. It provides a framework for fair and
        coherent training and evaluation of monotherapy drug response prediction models.
      homepage: https://github.com/daisybio/drevalpy/
      documentation: https://drevalpy.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/daisybio/drevalpy/
      doi: "10.1101/2025.05.26.655288"
      licence: ["MIT"]
      identifier: ""

input:
  - - models:
        type: string
        description: List of models, either specified with --models or via --baselines
    - response_data:
        type: file
        description: Pickled response data. For single-drug models, one model instance per unique drug id is needed.
  - name:
      type: string
      description: |
        Either models or baselines.

output:
  all_models:
    - "{models,baselines}*.txt":
        type: file
        description: |
          Contains either the list of all models or the list of all baselines, so that future processes can spawn one
          process per model. For single-drug models, there is one line per model-drug name combination.
        pattern: "{models,baselines}*.txt"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
containers:
  conda:
    linux/amd64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-a2b7a0d499377204_1/condalock
    linux/arm64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-c0ad67ba4f34e1c5_1/condalock
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/python_pip_drevalpy:a2b7a0d499377204
      build_id: bd-a2b7a0d499377204_1
    linux/arm64:
      name: community.wave.seqera.io/library/python_pip_drevalpy:c0ad67ba4f34e1c5
      build_id: bd-c0ad67ba4f34e1c5_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/python_pip_drevalpy:9f89d6d50658553e
      build_id: bd-9f89d6d50658553e_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/88/88d06bd843a342074e5def5c95e7d993cfe4a7f0acb7c41eb6c00e78d9ce8654/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/python_pip_drevalpy:1f164cef478f17cc
      build_id: bd-1f164cef478f17cc_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/3e/3ecc057132a723d9c2b97bec20727e0b83999fddc02842832efd7193a4690e30/data
