---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: evaluate_final
description: Evaluates the predictions from the final model
keywords:
  - evaluation
  - performance
  - predictions
  - final model
tools:
  - drevalpy:
      description: |
        drevalpy is the package underlying nf-core/drugresponseeval. It provides a framework for fair and
        coherent training and evaluation of monotherapy drug response prediction models.
      homepage: https://github.com/daisybio/drevalpy/
      documentation: https://drevalpy.readthedocs.io/en/latest/index.html
      tool_dev_url: https://github.com/daisybio/drevalpy/
      doi: "10.1101/2025.05.26.655288"
      licence: ["MIT"]
      identifier: ""

input:
  - - test_mode:
        type: string
        description: Specifies the test mode. One of LPO, LCO, LTO, LDO.
    - model_name:
        type: string
        description: Name of the model. Used to find out whether the model is a single-drug model.
    - pred_file:
        type: file
        description: File containing the true and predicted drug responses that this final trained model produced.

output:
  ch_individual_results:
    - "*.csv":
        type: file
        description: |
          Contains the individual result evaluation files per model: {model_name}_evaluation_results.csv,
          {model_name}_evaluation_results_per_drug.csv, {model_name}_evaluation_results_per_cl.csv, and
          {model_name}_true_vs_pred.csv.
        pattern: "*.csv"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
containers:
  conda:
    linux/amd64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-15b789664f3bd82d_1/condalock
    linux/arm64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-3e0785b5b12ace5a_1/condalock
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:15b789664f3bd82d
      build_id: bd-e3225eb976969752_3
    linux/arm64:
      name: community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:3e0785b5b12ace5a
      build_id: bd-3e0785b5b12ace5a_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:3a2daab6f1669afe
      build_id: bd-15b789664f3bd82d_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/6d/6dd942756556d881b3522aef53f63d24a977606d6dc629d23228f462c76a0dc6/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/matplotlib_numpy_pandas_python_pruned:de41fc123c6283bd
      build_id: bd-e1fbe7eefaa8d0b7_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/e4/e44bca044cacb8ef8eec56fc6414832e3c6f4c65e98546ceb827c7ac9d5392a5/data
