name: fit_curves
description: Fits curves using CurveCurator.
keywords:
  - curve fitting
  - dose-response data
  - harmonization
tools:
  - curve_curator:
      description: |
        CurveCurator is an open-source analysis platform for dose-dependent data sets. It fits a classical
        4-parameter equation to estimate effect potency, effect size, and the statistical significance
        of the observed response.
      homepage: https://github.com/kusterlab/curve_curator
      documentation: https://github.com/kusterlab/curve_curator
      tool_dev_url: https://github.com/kusterlab/curve_curator
      doi: "10.1038/s41467-023-43696-z"
      licence: ["Apache-2.9"]
      identifier: ""

input:
  - dataset_name:
      type: string
      description: Name of the dataset, e.g., CTRPv2
  - - dir_name:
        type: string
        description: Directory name where the toml file lies.
    - toml:
        type: file
        description: TOML file specifying the parameters for CurveCurator.
        pattern: "config.toml"
    - curvecurator_input:
        type: file
        description: Contains the input to CurveCurator, i.e., samples, drugs,
          doses, replicates
        pattern: "curvecurator_input.tsv"

output:
  path_to_curvecurator_out:
    - "curves.tsv":
        type: file
        description: |
          Contains fitted curves.
        pattern: "curves.tsv"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
containers:
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/python_pip_curve_curator:3b584472647bda92
      buildId: bd-3b584472647bda92_1
      scanId: sc-6af48bcbe83fbbbf_1
    linux/arm64:
      name: community.wave.seqera.io/library/python_pip_curve_curator:97424bed6a7f7435
      buildId: bd-97424bed6a7f7435_1
      scanId: sc-496561a8e367d080_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/python_pip_curve_curator:230cb19609b08d6b
      buildId: bd-230cb19609b08d6b_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/3c/3c2430fc8317997355ac2576512dbb971c9f04b81fadfc7ecf0a7d24d2520b67/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/python_pip_curve_curator:9eb2c4a784e83d96
      buildId: bd-9eb2c4a784e83d96_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/ea/ea3d3ad28e82f7502cea3e4dab169d83204d57af1ae85b71d1464f88caddc8db/data
  conda:
    linux/amd64:
      lock_file: modules/local/fit_curves/.conda-lock/linux-amd64-bd-3b584472647bda92_1.txt
    linux/arm64:
      lock_file: modules/local/fit_curves/.conda-lock/linux-arm64-bd-97424bed6a7f7435_1.txt
