---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: fit_curves
description: Fits curves using CurveCurator.
keywords:
  - curve fitting
  - dose-response data
  - harmonization
tools:
  - curve_curator:
      description: |
        CurveCurator is an open-source analysis platform for dose-dependent data sets. It fits a classical
        4-parameter equation to estimate effect potency, effect size, and the statistical significance
        of the observed response.
      homepage: https://github.com/kusterlab/curve_curator
      documentation: https://github.com/kusterlab/curve_curator
      tool_dev_url: https://github.com/kusterlab/curve_curator
      doi: "10.1038/s41467-023-43696-z"
      licence: ["Apache-2.9"]
      identifier: ""

input:
  - dataset_name:
      type: string
      description: Name of the dataset, e.g., CTRPv2
  - - dir_name:
        type: string
        description: Directory name where the toml file lies.
    - toml:
        type: file
        description: TOML file specifying the parameters for CurveCurator.
        pattern: "config.toml"
    - curvecurator_input:
        type: file
        description: Contains the input to CurveCurator, i.e., samples, drugs, doses, replicates
        pattern: "curvecurator_input.tsv"

output:
  path_to_curvecurator_out:
    - "curves.tsv":
        type: file
        description: |
          Contains fitted curves.
        pattern: "curves.tsv"
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@JudithBernett"
maintainers:
  - "@JudithBernett"
containers:
  conda:
    linux/amd64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-8f275bea1867edfd_1/condalock
    linux/arm64:
      lock_file: https://wave.seqera.io/v1alpha1/builds/bd-160cb0a74a2355bd_1/condalock
  docker:
    linux/amd64:
      name: community.wave.seqera.io/library/python_pip_curve-curator:8f275bea1867edfd
      build_id: bd-8f275bea1867edfd_1
    linux/arm64:
      name: community.wave.seqera.io/library/python_pip_curve-curator:160cb0a74a2355bd
      build_id: bd-160cb0a74a2355bd_1
  singularity:
    linux/amd64:
      name: oras://community.wave.seqera.io/library/python_pip_curve-curator:ca21c8b99edf33f1
      build_id: bd-ca21c8b99edf33f1_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/e7/e7b10d877585cdfd383daf38494baf81e52793282aeb3393088cf612e26a27b9/data
    linux/arm64:
      name: oras://community.wave.seqera.io/library/python_pip_curve-curator:43a2fee2721524e8
      build_id: bd-43a2fee2721524e8_1
      https: https://community-cr-prod.seqera.io/docker/registry/v2/blobs/sha256/8e/8ecce0dbba7b794a89b5b221dcf2321a6a0e1942bc50b51429bdf81fb35731f4/data
